apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
