apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: data-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
