apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: system
  name: minio-access
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: system
  name: data-service-minio-access
subjects:
- kind: ServiceAccount
  name: data-service-minio-sa
  namespace: application
roleRef:
  kind: Role
  name: minio-access
  apiGroup: rbac.authorization.k8s.io
